### ISSUE TITLE
Get db config from environment variables

### ISSUE THREAD

**Issue by zaharenkei** [zaharenkei/abstract-library-api#12]
Such variables will be available in the cloud

![Image](https://user-images.githubusercontent.com/68592735/217804443-435504d6-ef6d-44d3-bc10-12aa7fe3c503.png)

Create them locally in environment variables and try to get them from the app locally

**Comment by ZaharenkoOleg** [comment]
It could still be done this way , but for me there is not much difference, but visually I liked the option more as I did
    
    System.setProperty("spring.data.mongodb.host", HOST);
    System.setProperty("spring.data.mongodb.port", PORT);
    System.setProperty("spring.data.mongodb.database", DB);
    System.setProperty("spring.data.mongodb.username", USER);
    System.setProperty("spring.data.mongodb.password", PASS);

and accordingly in the property: 
spring.data.mongodb.password = ...
pring.data.mongodb.username = ...
spring.data.mongodb.database = ...
spring.data.mongodb.port = ...
spring.data.mongodb.host = ...
